### ISSUE TITLE
slow performance on big lists

### ISSUE THREAD

**Issue by bbfjumper** [mflova/lazy-type-hint#1]
i tried your tool with a dict of lists with diff. types (bytes, int, float, str), each list contains about 50000 elements. 
it took nearly 6 seconds to execute the follwowing command:

`th_data_dict = LazyTypeHintLive().from_data(data_dict, class_name="enc_data")`

but all in all a quiet nice tool

**Comment by mflova** [comment]
Thanks! Problem was fixed. Many speedup improvements were applied, which will improve not only long but also deep structures
